### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "password123"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "password123"
}

### LOGOUT
POST http://localhost:3000/auth/logout

### ADMIN - GET PRODUCTS
GET http://localhost:3000/admin/products

### ADMIN - CREATE PRODUCT
POST http://localhost:3000/admin/products
Content-Type: application/json

{
  "name": "Test Product3",
  "description": "Test Product Description",
  "price": 100,
  "category": "test",
  "imageUrl": "https://via.placeholder.com/150"
}

### ADMIN - UPDATE PRODUCT
PUT http://localhost:3000/admin/products/4
Content-Type: application/json

{
  "stock": 100
}

### CUSTOMER - GET ALL PRODUCTS
GET http://localhost:3000/customer/products

### CUSTOMER - GET ONE PRODUCT
GET http://localhost:3000/customer/products/3

### ADMIN - SEARCH PRODUCTS
GET http://localhost:3000/admin/search?name=Test Product

### CUSTOMER - SEARCH PRODUCTS
GET http://localhost:3000/customer/search?name=Test Product
